#module MyConstants

  if Rails.env == 'production'
    CHAT_LENGTH_CONSTANT = 120
    STARTING_MONEY_CONSTANT = 10
    TIMEOUT_CONSTANT = 300
    WAITFORPARTNER_TIMEOUT_CONSTANT = 1200
  else #development
    CHAT_LENGTH_CONSTANT = 30
    STARTING_MONEY_CONSTANT = 10
    TIMEOUT_CONSTANT = 60
    WAITFORPARTNER_TIMEOUT_CONSTANT = 120
  end
  
#end
  
  
  
  
  
